services:
  - type: web
    name: nawa-frontend
    env: static
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 